#%RAML 1.0 DataType
type: object
properties:
  acceptReject:
    displayName: Accept_Reject
    type: string
    required: true
    maxLength: 1
    example : A
  responseCode:
    displayName: Response Code 
    type: string
    required: true
    maxLength: 8
    example : Success
  customerName:
    displayName: Customer Name
    type: string
    required: true
    maxLength: 40
    example : John Doe
  customerRcifTieBreaker:
    displayName: Customer RCIF Tie Breaker
    type: integer
    required: true
    minimum: 000
    maximum: 999
    example : 123
  customerAddressLine1:
    displayName: Customer Address Line 1
    type: string 
    required: true
    maxLength: 40
    example : 2121 Warm Springs Rd 
  customerAddressLine2:
    displayName: Customer Address Line 2
    type: string 
    required: true
    maxLength: 40
    example : Suite 2500
  customerAddressLine3:
    displayName: Customer Address Line 3
    type: string 
    required: true
    maxLength: 40
    example :  Building 22
  customerCity:
    displayName: Customer City
    type: string 
    required: true
    maxLength: 35
    example : Jersey City
  state:
    displayName: State
    type: string 
    required: true
    maxLength: 2
    example : NJ
  zip:
    displayName: Zip
    type: integer 
    required: true
    minimum: 00000
    maximum: 9999999999
    example : 07306
  addressCorrectionCode:
    displayName: Address Correction Code  
    type: string 
    required: true
    enum: [N, ] 
    example : N
  customerForeignMailCodeFlag:
    displayName: Customer Foreign Mail Code Flag
    type: string 
    required: true
    maxLength: 1
    example : Y
  taxId:
    displayName: Tax Id
    type: integer 
    required: true
    minimum: 000000000
    maximum: 999999999
    example : 183456798
  customerLvlComment1:
    displayName: Customer LVL Comment 1
    type: string 
    required: true
    maxLength: 40
    example : some text description
  customerLvlComment2:
    displayName: Customer LVL Comment 2
    type: string 
    required: true
    maxLength: 40
    example : some text description 
  customerDescriptionCodes:
    displayName: Customer Description Codes
    type: array 
    required: true
    items: 
      type: object
      properties:
        descriptionCode:
          displayName: Description Code
          type: integer
          required: true
          minimum : 000
          maximum : 999

    example: [{"descriptionCode": 302},{"descriptionCode": 708},{"descriptionCode": 501},{"descriptionCode": 888},{"descriptionCode": 230}]
    
  birthDate:
    displayName: Birth Date
    type: datetime 
    required: true
    example : "2015-08-19T00:00:00Z"
  crfStatus:
    displayName: CRF Status
    type: string 
    required: true
    maxLength: 2
    example : YS
  customerFirstName:
    displayName: Customer First Name
    type: string 
    required: true
    maxLength: 25
    example : John
  customerMiddleName:
    displayName: Customer Middle Name
    type: string 
    required: true
    maxLength: 25
    example : NA
  customerLastName:
    displayName: Customer Last Name
    type: string 
    required: true
    maxLength: 25
    example : Doe
  genderCode:
    displayName: Gender Code
    type: string 
    required: true
    maxLength: 1
    example : M
  premierSourceCode:
    displayName: Premier Source Code
    type: string 
    required: true
    maxLength: 5
    example : TR013
  chargeoffFoundIndicator:
    displayName: Chargeoff Found Indicator
    type: string 
    required: true
    maxLength: 1
    example : N
  privacyCode:
    displayName: Privacy Code
    type: string 
    required: true
    maxLength: 1
    enum: [Y,A,B, ]
    example : A
  customerId1IssueDate:
    displayName: Customer ID1 Issue Date 
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  customerId1ExpirationDate:
    displayName: Customer ID1 Expiration Date 
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  customerId1State:
    displayName: Customer ID1 State
    type: string 
    required: true
    maxLength: 2
    example : NJ
  customerId1DriversLicenseNbr:
    displayName: Customer ID1 Drivers License Number
    type: string 
    required: true
    maxLength: 16
    example : A132178910146187
  customerId1Type:
    displayName: Customer ID1 Type
    type: string 
    required: true
    maxLength: 4
    example : LICN
  customerId2IssueDate:
    displayName: Customer ID2 Issue Date 
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  customerId2ExpirationDate:
    displayName: Customer ID2 Expiration Date 
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  customerId2IssueCountry:
    displayName: Customer ID2 Issue Country 
    type: string 
    required: true
    maxLength: 2
    example : US
  customerId2Number:
    displayName: Customer ID2 Number
    type: string 
    required: true
    maxLength: 20
    example : F331232
  customerId2Type:
    displayName: Customer ID2 Type
    type: string 
    required: true
    maxLength: 4
    example : PASP
  secondaryIdIssuer:
    displayName: Secondary ID Issuer
    type: string 
    required: true
    maxLength: 8
    example : DHS
  countryOfCitizenship:
    displayName: Country of Citizenship
    type: string 
    required: true
    maxLength: 2
    example : US
  citizenForeignEntity:
    displayName: Citizen/Foreign Enttity
    type: string 
    required: true
    maxLength: 1
    example : N
  firstContactDate:
    displayName: First Contract Date
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  lastMaintenanceDate:
    displayName: Last Maintenance Date
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  dateOfDeath:
    displayName: Date of Death
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  countryOfBirth:
    displayName: Country Of Birth
    type: string 
    required: true
    maxLength: 2
    example : US
  ibn:
    displayName: IBN
    type: string 
    required: true
    maxLength: 10
    example : GAD12346
  employer:
    displayName: Employer
    type: string 
    required: true
    maxLength: 40
    example : Regions Bank
  employmentDate:
    displayName: Employment Date
    type: datetime 
    required: true
    example : "2015-08-19T15:10:16Z"
  employmentStatusCode:
    displayName: Employment Status Code
    type: string 
    required: true
    maxLength: 1
    example : I
  employmentAddressLine1:
    displayName: Employment Address Line 1
    type: string 
    required: true
    maxLength: 40
    example : 15000 Summit Tower Blvd
  employmentAddressLine2:
    displayName: Employment Address Line 2
    type: string 
    required: true
    maxLength: 40
    example : Suite 2300
  employmentAddressLine3:
    displayName: Employment Address Line 3
    type: string 
    required: true
    maxLength: 40
    example : Building 89
  employerCityCountry:
    displayName: Employer Country
    type: string 
    required: true
    maxLength: 35
    example : Birmingham Unites States
  employerState:
    displayName: Employer State
    type: string 
    required: true
    maxLength: 2
    example : AL
  employeeZip:
    displayName: Employee Zip
    type: string 
    required: true
    maxLength: 10
    example : USAL66457
  employeeForeignMailCodeFlag:
    displayName: Employee Foreign Mail Falg
    type: string 
    required: true
    maxLength: 1
    example : N
  occupationCode:
    displayName: Occupation Code
    type: string 
    required: true
    maxLength: 5
    example : Z056
  studentStatus:
    displayName: Student Status
    type: string 
    required: true
    maxLength: 1
    example : N
  studentSchoolName:
    displayName: Student School Name
    type: string 
    required: true
    maxLength: 50
    example : Texas University
  ownRentCode:
    displayName: Own/Rent Code
    type: string 
    required: true
    maxLength: 1
    example : R
  privateWealthCode:
    displayName: Private Wealth Code
    type: string 
    required: true
    maxLength: 1
    example : R
  wealthSourceCode:
    displayName: Wealth Source Code
    type: string 
    required: true
    maxLength: 1
    example : X
  wealthSourceDescription:
    displayName: Wealth Source Description
    type: string 
    required: true
    maxLength: 50
    example : Salary , Investment , Trades 
  referralCode:
    displayName: ReferralCode
    type: string 
    required: true
    maxLength: 1
    enum: [O, ]
    example : O
  customerEmailAddressInfo:
    displayName: Customer Email Address Info
    type: array 
    required: true
    items: !include email.raml
    
  customerPhoneNumberInfo:
    displayName: Customer Phone Number Info
    type: array 
    required: true
    items: !include phone.raml

  dualCitizenCountry:
    displayName: Dual Citizen Country
    type: string 
    required: true
    maxLength: 2
    example : IN
  visaType:
    displayName: Visa Type
    type: string 
    required: true
    maxLength: 10
    example : L1B ICT
  residencyApplication:
    displayName: Residency Application
    type: string 
    required: true
    maxLength: 1
    example : N
  countryOfResidence:
    displayName: Country Of Residence
    type: string 
    required: true
    maxLength: 5
    example : USA
  nraSavingsCode:
    displayName: NRA Savings Code
    type: string 
    required: true
    maxLength: 1
    example : V
  nraExpenseCode:
    displayName: NRA Expense Code
    type: string 
    required: true
    maxLength: 1
    example : Z
  nraDepositCode:
    displayName: NRA Deposit Code
    type: string 
    required: true
    maxLength: 1
    example : T
  nraTravelCode:
    displayName: NRA Travel Code
    type: string 
    required: true
    maxLength: 1
    example : G
  nraOtherRequirements:
    displayName: NRA Other Requirements
    type: string 
    required: true
    maxLength: 1
    example : H
  nraOtherRequirementsDesc:
    displayName: NRA Other Requirements Description
    type: string 
    required: true
    maxLength: 50
    example : Some description on NRA
  nraPresenceCode:
    displayName: NRA Presence Code
    type: string 
    required: true
    maxLength: 1
    example : K
  nraPresenceDesc:
    displayName: NRA Presence Desc
    type: string 
    required: true
    maxLength: 50
    example : Out of country
  nraStayCode:
    displayName: NRA Stay Code
    type: string 
    required: true
    maxLength: 1
    example : U
  studentSupportCode:
    displayName: Student Support Code
    type: string 
    required: true
    maxLength: 1
    example : Y
  studentSupportDesc:
    displayName: Student Support Desc
    type: string 
    required: true
    maxLength: 100
    example : Some description on Student support procedures
  pepIndicator:
    displayName: PEP Indicator
    type: string 
    required: true
    maxLength: 1
    example : C
  pepStatus:
    displayName: PEP Status
    type: string 
    required: true
    maxLength: 1
    example : A 
  pepRelationship:
    displayName: PEP Relationship
    type: string 
    required: true
    maxLength: 1
    example : D
  pepPosition:
    displayName: PEP Position
    type: string 
    required: true
    maxLength: 40
    example : Some description on PEP Position
  pepCountry:
    displayName: PEP Country
    type: string 
    required: true
    maxLength: 3
    example : USA
  accessCheckCardFlag:
    displayName: Access Check Card Flag
    type: string 
    required: true
    maxLength: 1
    example : Y
  accessChecksFlag:
    displayName: Access Checks Flag
    type: string 
    required: true
    maxLength: 1
    example : Y
  accessOnlineBankingFlag:
    displayName: Access Online Banking Flag
    type: string 
    required: true
    maxLength: 1
    example : Y
  accessWireTransferFlag:
    displayName: Access Wire Transfer Flag
    type: string 
    required: true
    maxLength: 1
    example : N
  accessDepositCaptrueFlag:
    displayName: Access Deposit Capture Flag
    type: string 
    required: true
    maxLength: 1
    example : N
  accessCashFlag:
    displayName: Access Cash Flag
    type: string 
    required: true
    maxLength: 1
    example : N
  monthlyCashDepositCode:
    displayName: Monthly Cash Deposit Code
    type: string 
    required: true
    maxLength: 1
    example : D
  monthlyCashWithdrawalCode:
    displayName: Monthly Cash Withdrawal Code
    type: string 
    required: true
    maxLength: 1
    example : E 
  wireTransferCode:
    displayName: Wire Transfer Code
    type: string 
    required: true
    maxLength: 1
    example : L
  wireTransferCountry:
    displayName: Wire Transfer Country
    type: array 
    required: true
    example : [IND,USA,AUS,UK,CAN]
  wireInCode:
    displayName: Wire In Code
    type: string 
    required: true
    maxLength: 1
    example : I
  wireOutCode:
    displayName: Wire Out Code
    type: string 
    required: true
    maxLength: 1
    example : O
  cifNumber:
    displayName: CIF Number
    type: string 
    required: true
    maxLength: 13
    example : CV12345A12
  occupationOtherDesc:
    displayName: Occupation Other Desc
    type: string 
    required: true
    maxLength: 40
    example : Some description on the Occupation
  cddRiskSide:
    displayName: CDD Risk Side
    type: string 
    required: true
    maxLength: 1
    example : X
  