      #%RAML 1.0 DataType
    type: object
    properties:  
        emailAddress:
          displayName: Email Address
          type: string
          required: true
          maxLength: 50
          example: someone@gmail.com
        emailType:
          displayName: Email Type
          type: string
          required: true
          maxLength: 1
          example: H
        emailRestrict1Flag:
          displayName: Email Restrict-1 Flag
          type: string
          required: true
          maxLength: 1
          example: Y
        emailRestrict2Flag:
          displayName: Email Restrict-2 Flag
          type: string
          required: true
          maxLength: 1
          example: N