      #%RAML 1.0 DataType
type: object
properties: 
      phoneNumber:
        displayName: Phone Number
        type: integer
        required: true
        minimum: 0000000000
        maximum: 9999999999
        example: 7022018879
      prefix:
        displayName: Prefix
        type: integer
        required: true
        minimum: 0000000
        maximum: 9999999
        example: 1 
      extension:
        displayName: Extension
        type: integer
        required: true
        minimum: 00000
        maximum: 55555
        example: 4040
      primaryFlag:
        displayName: Primary Flag
        type: string
        required: true
        maxLength: 1
        example: Y
      customerReference:
        displayName: Customer Reference
        type: integer
        required: true
        minimum: 0000000000
        maximum: 9999999999
        example: 1238749
      bestTimeToCall:
        displayName: Best Time to Call
        type: string
        required: true
        maxLength: 1
        example: N  
      deviceType:
        displayName: Device Type
        type: string
        required: true
        maxLength: 1
        example: S
      smsTextFlag:
        displayName: SMS Text Flag
        type: string
        required: true
        maxLength: 1
        example: Y  
      faxFlag:
        displayName: Fax Flag
        type: string
        required: true
        maxLength: 1
        example: N
      teleUseRest1Flag:
        displayName: Tele Use Rest1 Flag
        type: string
        required: true
        maxLength: 1
        example: Y
      teleUseRest2Flag:
        displayName: Tele Use Rest2 Flag
        type: string
        required: true
        maxLength: 1
        example: N