#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/4824eec2-09a3-48f3-91d1-28f68c378880 # 

title: customer-profile-sys-api
version: v1

types:
  customerProfile: !include dataTypes/customerProfile.raml
  customerSearch: !include dataTypes/customerSearch.raml
traits: 
  client-id-enf : !include dataTypes/policy.raml

/customer:
  /profile:
    /rcifNumber:
      get:
        is: [client-id-enf]
        description: get customer profile by passing Customer RCIF Number
        headers: 
          rcifNumber:
            displayName: Customer RCIF Number
            type: string 
            required: true
          requestedChannel:
            displayName: Requested Channel
            type: string 
            required: true
          associateId:
            displayName: Associate's ID
            type: string 
            required: true
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/customerProfile.json
    /tin:
      get:
        is: [client-id-enf]
        description: search customer by passing Customer SSN/TIN
        headers: 
          tinId:
            displayName: Customer SSN / TIN
            type: string 
            required: true
          bankNumber:
            displayName: Bank Number
            type: string
            required: true
          personalBusinessCode:
            displayName: Customer Personal/Business Code
            type: string
            required: true
          associateId:
            displayName: Associate's ID
            type: string 
            required: true
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/customerSearch.json
    /accountNumber:
      get:
        is: [client-id-enf]
        description: search customer by passing Customer Account number
        headers: 
          bankNumber:
            displayName: Bank Number
            type: string 
            required: true
          applicationId:
            displayName: Application ID
            type: string 
            required: false
          accountNumber:
            displayName: Customer Account Number 
            type: string 
            required: true
          associateId:
            displayName: Associate's ID
            type: string 
            required: true

        responses: 
          200:
            body: 
              application/json:
                example: !include examples/customerSearch.json
    /sysId:
      get:
        is: [client-id-enf]
        description: get customer profile by passing Customer Master System ID
        headers: 
          sysId:
            displayName: Customer Master System ID
            type: string 
            required: true
          requestedChannel:
            displayName: Requested Channel
            type: string 
            required: true
          associateId:
            displayName: Associate's ID
            type: string 
            required: true
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/customerProfile.json
    /name:
      get:
        is: [client-id-enf]
        description: search customer by passing Customer Name
        headers: 
          name:
            displayName: Customer Name
            type: string
            required: true
          associateId:
            displayName: Associate's ID
            type: string 
            required: true
          bankNumber:
            displayName: Bank Number
            type: string
            required: true
          personalBusinessCode:
            displayName: Customer Personal/Business Code
            type: string
            required: true
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/customerSearch.json