#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/387b1cf5-8fb0-4ca6-bf90-bf504f06ea85 # 

title: mule-basic-endpoint
version: v1

traits: 
  client_id_enf : !include traits/trait-api-security.raml

/basicep:
  description: test api for cicd
  get:
    is: [client_id_enf]
    responses: 
      200:
        body: 
          application/json:
            example: { "Response" : "CICD Test Successful" }